[global.databases]
database_url={ url = "postgres://ewan:223344@localhost/surveys" }


[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "critical"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
limits = { forms = 32768 }